### 5/13/14 ###
# Reproducible Research: Peer Assessment 1


## Loading and preprocessing the data

```{r loading_data}

input <- read.table("activity.csv",sep=",",header=T)
head(input)
table(input$date)
intervals <- unique(input$interval)
days <- unique(input$date)

```

## What is mean total number of steps taken per day?
``` {r mean_total_steps}

hist(input$steps,col="red",xlab="Number of steps",main="Histogram of steps taken")
require(plyr)
results <- ddply(input,"date",function(x) {
	data.frame(mean.steps=mean(x$steps,na.rm=F),median.steps=median(x$steps,na.rm=F))
})
head(results)

```

## What is the average daily activity pattern?
``` {r average_daily_activity }

out <- ddply(input,"interval",function(x) {
	data.frame(mean.steps=mean(x$steps,na.rm=T))
})
head(out)
plot(out$interval,out$mean.steps,type="l",xlab="5 mt interval",ylab="Average # of steps (over all days)")
subset(out,mean.steps==max(mean.steps))
### the 104th 5 minute interval contains the max # steps, averaged over days

```

## Imputing missing values
``` {r missing_values}

sum(!complete.cases(input))   ### total number of rows with NAs = 2304 
input2 <- merge(input,out,by="interval")
head(input2)
### fill in NAs with mean for that 5 mt interval
input3 <- subset(data.frame(t(apply(as.matrix(input2),1,function(x) {
	x[2]=ifelse(is.na(x[2]),x[4],x[2])
	return(x)
})),check.names=F),select=c(steps,date,interval))
input3$steps <-  as.numeric(levels(input3$steps))[input3$steps] #as.integer(input3$steps); 
### the new dataset with missing data filled in !
head(input3)   
### check to make sure there are no NAs
sum(!complete.cases(input3))
hist(input3$steps,col="red",xlab="Number of steps",main="Histogram of steps taken")
### The frequency in the first bin in the histogram is more, when missing data is filled in
results2 <- ddply(input3,"date",function(x) {
	data.frame(mean.steps=mean(x$steps,na.rm=F),median.steps=median(x$steps,na.rm=F))
})
head(results2)

```

## Are there differences in activity patterns between weekdays and weekends?
``` {r weekdays_weekends}

input3$weekday <- weekdays(as.Date(input3$date))
input3$is.weekday <- factor(ifelse(grepl("^s",ignore.case=T,input3$weekday),"weekend","weekday"),levels=c("weekday","weekend"))
out2 <- ddply(input3,c("interval","is.weekday"),function(x) {
	data.frame(mean.steps=mean(x$steps,na.rm=T))
})
head(out2)
require(lattice)
out2$interval <- as.numeric(levels(out2$interval))[out2$interval]  #as.numeric(as.character(out2$interval))
xyplot(mean.steps~interval|is.weekday,data=out2,layout=c(1,2),type="l",ylab="Average number of steps",xlab="Interval")

```



